/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as FindGigsRouteImport } from './routes/find-gigs'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SignedinRouteImport } from './routes/_signedin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayRefRouteImport } from './routes/pay.$ref'
import { Route as FindGigsIdRouteImport } from './routes/find-gigs.$id'
import { Route as BookHandleRouteImport } from './routes/book.$handle'
import { Route as SignedinWelcomeRouteImport } from './routes/_signedin/welcome'
import { Route as SignedinPostGigRouteImport } from './routes/_signedin/post-gig'
import { Route as SignedinMyRosterRouteImport } from './routes/_signedin/my-roster'
import { Route as SignedinMyGigsRouteImport } from './routes/_signedin/my-gigs'
import { Route as SignedinMyApplicationsRouteImport } from './routes/_signedin/my-applications'
import { Route as SignedinConciergeRouteImport } from './routes/_signedin/concierge'
import { Route as SignedinArtistRouteImport } from './routes/_signedin/artist'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as BookConfirmRefRouteImport } from './routes/book.confirm.$ref'
import { Route as ApiPublicQuoteRequestRouteImport } from './routes/api/public/quote-request'
import { Route as ApiPublicGigsRouteImport } from './routes/api/public/gigs'
import { Route as ApiPublicDistanceRouteImport } from './routes/api/public/distance'
import { Route as ApiPublicBookingsRouteImport } from './routes/api/public/bookings'
import { Route as ApiPublicArtistsRouteImport } from './routes/api/public/artists'
import { Route as SignedinMyGigsIdRouteImport } from './routes/_signedin/my-gigs.$id'
import { Route as SignedinArtistProfileRouteImport } from './routes/_signedin/artist.profile'
import { Route as SignedinArtistIntelligenceRouteImport } from './routes/_signedin/artist.intelligence'
import { Route as SignedinArtistCareerRouteImport } from './routes/_signedin/artist.career'
import { Route as AuthenticatedAdminVerifyRouteImport } from './routes/_authenticated/admin.verify'
import { Route as AuthenticatedAdminPromotersRouteImport } from './routes/_authenticated/admin.promoters'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin.pipeline'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin.packages'
import { Route as AuthenticatedAdminGigsRouteImport } from './routes/_authenticated/admin.gigs'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin.calendar'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as ApiPublicDepositsRefRouteImport } from './routes/api/public/deposits.$ref'
import { Route as ApiPublicCronPaymentRemindersRouteImport } from './routes/api/public/cron/payment-reminders'
import { Route as ApiPublicCronDecisionEngineRouteImport } from './routes/api/public/cron/decision-engine'
import { Route as ApiPublicBookingsRefRouteImport } from './routes/api/public/bookings.$ref'
import { Route as SignedinArtistIntelligenceOnboardingRouteImport } from './routes/_signedin/artist.intelligence.onboarding'
import { Route as AuthenticatedAdminEventsIdRouteImport } from './routes/_authenticated/admin.events.$id'
import { Route as AuthenticatedAdminBookingsNewRouteImport } from './routes/_authenticated/admin.bookings.new'
import { Route as AuthenticatedAdminBookingsIdRouteImport } from './routes/_authenticated/admin.bookings.$id'

const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const FindGigsRoute = FindGigsRouteImport.update({
  id: '/find-gigs',
  path: '/find-gigs',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedinRoute = SignedinRouteImport.update({
  id: '/_signedin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRefRoute = PayRefRouteImport.update({
  id: '/pay/$ref',
  path: '/pay/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const FindGigsIdRoute = FindGigsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FindGigsRoute,
} as any)
const BookHandleRoute = BookHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => BookRoute,
} as any)
const SignedinWelcomeRoute = SignedinWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => SignedinRoute,
} as any)
const SignedinPostGigRoute = SignedinPostGigRouteImport.update({
  id: '/post-gig',
  path: '/post-gig',
  getParentRoute: () => SignedinRoute,
} as any)
const SignedinMyRosterRoute = SignedinMyRosterRouteImport.update({
  id: '/my-roster',
  path: '/my-roster',
  getParentRoute: () => SignedinRoute,
} as any)
const SignedinMyGigsRoute = SignedinMyGigsRouteImport.update({
  id: '/my-gigs',
  path: '/my-gigs',
  getParentRoute: () => SignedinRoute,
} as any)
const SignedinMyApplicationsRoute = SignedinMyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => SignedinRoute,
} as any)
const SignedinConciergeRoute = SignedinConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => SignedinRoute,
} as any)
const SignedinArtistRoute = SignedinArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => SignedinRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const BookConfirmRefRoute = BookConfirmRefRouteImport.update({
  id: '/confirm/$ref',
  path: '/confirm/$ref',
  getParentRoute: () => BookRoute,
} as any)
const ApiPublicQuoteRequestRoute = ApiPublicQuoteRequestRouteImport.update({
  id: '/api/public/quote-request',
  path: '/api/public/quote-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGigsRoute = ApiPublicGigsRouteImport.update({
  id: '/api/public/gigs',
  path: '/api/public/gigs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDistanceRoute = ApiPublicDistanceRouteImport.update({
  id: '/api/public/distance',
  path: '/api/public/distance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtistsRoute = ApiPublicArtistsRouteImport.update({
  id: '/api/public/artists',
  path: '/api/public/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedinMyGigsIdRoute = SignedinMyGigsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SignedinMyGigsRoute,
} as any)
const SignedinArtistProfileRoute = SignedinArtistProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SignedinArtistRoute,
} as any)
const SignedinArtistIntelligenceRoute =
  SignedinArtistIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => SignedinArtistRoute,
  } as any)
const SignedinArtistCareerRoute = SignedinArtistCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => SignedinArtistRoute,
} as any)
const AuthenticatedAdminVerifyRoute =
  AuthenticatedAdminVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromotersRoute =
  AuthenticatedAdminPromotersRouteImport.update({
    id: '/promoters',
    path: '/promoters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGigsRoute = AuthenticatedAdminGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicDepositsRefRoute = ApiPublicDepositsRefRouteImport.update({
  id: '/api/public/deposits/$ref',
  path: '/api/public/deposits/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronPaymentRemindersRoute =
  ApiPublicCronPaymentRemindersRouteImport.update({
    id: '/api/public/cron/payment-reminders',
    path: '/api/public/cron/payment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDecisionEngineRoute =
  ApiPublicCronDecisionEngineRouteImport.update({
    id: '/api/public/cron/decision-engine',
    path: '/api/public/cron/decision-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookingsRefRoute = ApiPublicBookingsRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => ApiPublicBookingsRoute,
} as any)
const SignedinArtistIntelligenceOnboardingRoute =
  SignedinArtistIntelligenceOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => SignedinArtistIntelligenceRoute,
  } as any)
const AuthenticatedAdminEventsIdRoute =
  AuthenticatedAdminEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsNewRoute =
  AuthenticatedAdminBookingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminBookingsRoute,
  } as any)
const AuthenticatedAdminBookingsIdRoute =
  AuthenticatedAdminBookingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBookingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRouteWithChildren
  '/find-gigs': typeof FindGigsRouteWithChildren
  '/request-quote': typeof RequestQuoteRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/artist': typeof SignedinArtistRouteWithChildren
  '/concierge': typeof SignedinConciergeRoute
  '/my-applications': typeof SignedinMyApplicationsRoute
  '/my-gigs': typeof SignedinMyGigsRouteWithChildren
  '/my-roster': typeof SignedinMyRosterRoute
  '/post-gig': typeof SignedinPostGigRoute
  '/welcome': typeof SignedinWelcomeRoute
  '/book/$handle': typeof BookHandleRoute
  '/find-gigs/$id': typeof FindGigsIdRoute
  '/pay/$ref': typeof PayRefRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRouteWithChildren
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/gigs': typeof AuthenticatedAdminGigsRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/admin/verify': typeof AuthenticatedAdminVerifyRoute
  '/artist/career': typeof SignedinArtistCareerRoute
  '/artist/intelligence': typeof SignedinArtistIntelligenceRouteWithChildren
  '/artist/profile': typeof SignedinArtistProfileRoute
  '/my-gigs/$id': typeof SignedinMyGigsIdRoute
  '/api/public/artists': typeof ApiPublicArtistsRoute
  '/api/public/bookings': typeof ApiPublicBookingsRouteWithChildren
  '/api/public/distance': typeof ApiPublicDistanceRoute
  '/api/public/gigs': typeof ApiPublicGigsRoute
  '/api/public/quote-request': typeof ApiPublicQuoteRequestRoute
  '/book/confirm/$ref': typeof BookConfirmRefRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/artist/intelligence/onboarding': typeof SignedinArtistIntelligenceOnboardingRoute
  '/api/public/bookings/$ref': typeof ApiPublicBookingsRefRoute
  '/api/public/cron/decision-engine': typeof ApiPublicCronDecisionEngineRoute
  '/api/public/cron/payment-reminders': typeof ApiPublicCronPaymentRemindersRoute
  '/api/public/deposits/$ref': typeof ApiPublicDepositsRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRouteWithChildren
  '/find-gigs': typeof FindGigsRouteWithChildren
  '/request-quote': typeof RequestQuoteRoute
  '/artist': typeof SignedinArtistRouteWithChildren
  '/concierge': typeof SignedinConciergeRoute
  '/my-applications': typeof SignedinMyApplicationsRoute
  '/my-gigs': typeof SignedinMyGigsRouteWithChildren
  '/my-roster': typeof SignedinMyRosterRoute
  '/post-gig': typeof SignedinPostGigRoute
  '/welcome': typeof SignedinWelcomeRoute
  '/book/$handle': typeof BookHandleRoute
  '/find-gigs/$id': typeof FindGigsIdRoute
  '/pay/$ref': typeof PayRefRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRouteWithChildren
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/gigs': typeof AuthenticatedAdminGigsRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/admin/verify': typeof AuthenticatedAdminVerifyRoute
  '/artist/career': typeof SignedinArtistCareerRoute
  '/artist/intelligence': typeof SignedinArtistIntelligenceRouteWithChildren
  '/artist/profile': typeof SignedinArtistProfileRoute
  '/my-gigs/$id': typeof SignedinMyGigsIdRoute
  '/api/public/artists': typeof ApiPublicArtistsRoute
  '/api/public/bookings': typeof ApiPublicBookingsRouteWithChildren
  '/api/public/distance': typeof ApiPublicDistanceRoute
  '/api/public/gigs': typeof ApiPublicGigsRoute
  '/api/public/quote-request': typeof ApiPublicQuoteRequestRoute
  '/book/confirm/$ref': typeof BookConfirmRefRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/artist/intelligence/onboarding': typeof SignedinArtistIntelligenceOnboardingRoute
  '/api/public/bookings/$ref': typeof ApiPublicBookingsRefRoute
  '/api/public/cron/decision-engine': typeof ApiPublicCronDecisionEngineRoute
  '/api/public/cron/payment-reminders': typeof ApiPublicCronPaymentRemindersRoute
  '/api/public/deposits/$ref': typeof ApiPublicDepositsRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_signedin': typeof SignedinRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRouteWithChildren
  '/find-gigs': typeof FindGigsRouteWithChildren
  '/request-quote': typeof RequestQuoteRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_signedin/artist': typeof SignedinArtistRouteWithChildren
  '/_signedin/concierge': typeof SignedinConciergeRoute
  '/_signedin/my-applications': typeof SignedinMyApplicationsRoute
  '/_signedin/my-gigs': typeof SignedinMyGigsRouteWithChildren
  '/_signedin/my-roster': typeof SignedinMyRosterRoute
  '/_signedin/post-gig': typeof SignedinPostGigRoute
  '/_signedin/welcome': typeof SignedinWelcomeRoute
  '/book/$handle': typeof BookHandleRoute
  '/find-gigs/$id': typeof FindGigsIdRoute
  '/pay/$ref': typeof PayRefRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRouteWithChildren
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/gigs': typeof AuthenticatedAdminGigsRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/_authenticated/admin/verify': typeof AuthenticatedAdminVerifyRoute
  '/_signedin/artist/career': typeof SignedinArtistCareerRoute
  '/_signedin/artist/intelligence': typeof SignedinArtistIntelligenceRouteWithChildren
  '/_signedin/artist/profile': typeof SignedinArtistProfileRoute
  '/_signedin/my-gigs/$id': typeof SignedinMyGigsIdRoute
  '/api/public/artists': typeof ApiPublicArtistsRoute
  '/api/public/bookings': typeof ApiPublicBookingsRouteWithChildren
  '/api/public/distance': typeof ApiPublicDistanceRoute
  '/api/public/gigs': typeof ApiPublicGigsRoute
  '/api/public/quote-request': typeof ApiPublicQuoteRequestRoute
  '/book/confirm/$ref': typeof BookConfirmRefRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/_authenticated/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/_authenticated/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/_signedin/artist/intelligence/onboarding': typeof SignedinArtistIntelligenceOnboardingRoute
  '/api/public/bookings/$ref': typeof ApiPublicBookingsRefRoute
  '/api/public/cron/decision-engine': typeof ApiPublicCronDecisionEngineRoute
  '/api/public/cron/payment-reminders': typeof ApiPublicCronPaymentRemindersRoute
  '/api/public/deposits/$ref': typeof ApiPublicDepositsRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/find-gigs'
    | '/request-quote'
    | '/admin'
    | '/artist'
    | '/concierge'
    | '/my-applications'
    | '/my-gigs'
    | '/my-roster'
    | '/post-gig'
    | '/welcome'
    | '/book/$handle'
    | '/find-gigs/$id'
    | '/pay/$ref'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/gigs'
    | '/admin/packages'
    | '/admin/pipeline'
    | '/admin/promoters'
    | '/admin/verify'
    | '/artist/career'
    | '/artist/intelligence'
    | '/artist/profile'
    | '/my-gigs/$id'
    | '/api/public/artists'
    | '/api/public/bookings'
    | '/api/public/distance'
    | '/api/public/gigs'
    | '/api/public/quote-request'
    | '/book/confirm/$ref'
    | '/admin/'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/events/$id'
    | '/artist/intelligence/onboarding'
    | '/api/public/bookings/$ref'
    | '/api/public/cron/decision-engine'
    | '/api/public/cron/payment-reminders'
    | '/api/public/deposits/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/find-gigs'
    | '/request-quote'
    | '/artist'
    | '/concierge'
    | '/my-applications'
    | '/my-gigs'
    | '/my-roster'
    | '/post-gig'
    | '/welcome'
    | '/book/$handle'
    | '/find-gigs/$id'
    | '/pay/$ref'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/gigs'
    | '/admin/packages'
    | '/admin/pipeline'
    | '/admin/promoters'
    | '/admin/verify'
    | '/artist/career'
    | '/artist/intelligence'
    | '/artist/profile'
    | '/my-gigs/$id'
    | '/api/public/artists'
    | '/api/public/bookings'
    | '/api/public/distance'
    | '/api/public/gigs'
    | '/api/public/quote-request'
    | '/book/confirm/$ref'
    | '/admin'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/events/$id'
    | '/artist/intelligence/onboarding'
    | '/api/public/bookings/$ref'
    | '/api/public/cron/decision-engine'
    | '/api/public/cron/payment-reminders'
    | '/api/public/deposits/$ref'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_signedin'
    | '/auth'
    | '/book'
    | '/find-gigs'
    | '/request-quote'
    | '/_authenticated/admin'
    | '/_signedin/artist'
    | '/_signedin/concierge'
    | '/_signedin/my-applications'
    | '/_signedin/my-gigs'
    | '/_signedin/my-roster'
    | '/_signedin/post-gig'
    | '/_signedin/welcome'
    | '/book/$handle'
    | '/find-gigs/$id'
    | '/pay/$ref'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/gigs'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/admin/promoters'
    | '/_authenticated/admin/verify'
    | '/_signedin/artist/career'
    | '/_signedin/artist/intelligence'
    | '/_signedin/artist/profile'
    | '/_signedin/my-gigs/$id'
    | '/api/public/artists'
    | '/api/public/bookings'
    | '/api/public/distance'
    | '/api/public/gigs'
    | '/api/public/quote-request'
    | '/book/confirm/$ref'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/bookings/$id'
    | '/_authenticated/admin/bookings/new'
    | '/_authenticated/admin/events/$id'
    | '/_signedin/artist/intelligence/onboarding'
    | '/api/public/bookings/$ref'
    | '/api/public/cron/decision-engine'
    | '/api/public/cron/payment-reminders'
    | '/api/public/deposits/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SignedinRoute: typeof SignedinRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRouteWithChildren
  FindGigsRoute: typeof FindGigsRouteWithChildren
  RequestQuoteRoute: typeof RequestQuoteRoute
  PayRefRoute: typeof PayRefRoute
  ApiPublicArtistsRoute: typeof ApiPublicArtistsRoute
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRouteWithChildren
  ApiPublicDistanceRoute: typeof ApiPublicDistanceRoute
  ApiPublicGigsRoute: typeof ApiPublicGigsRoute
  ApiPublicQuoteRequestRoute: typeof ApiPublicQuoteRequestRoute
  ApiPublicCronDecisionEngineRoute: typeof ApiPublicCronDecisionEngineRoute
  ApiPublicCronPaymentRemindersRoute: typeof ApiPublicCronPaymentRemindersRoute
  ApiPublicDepositsRefRoute: typeof ApiPublicDepositsRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-gigs': {
      id: '/find-gigs'
      path: '/find-gigs'
      fullPath: '/find-gigs'
      preLoaderRoute: typeof FindGigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signedin': {
      id: '/_signedin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SignedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$ref': {
      id: '/pay/$ref'
      path: '/pay/$ref'
      fullPath: '/pay/$ref'
      preLoaderRoute: typeof PayRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-gigs/$id': {
      id: '/find-gigs/$id'
      path: '/$id'
      fullPath: '/find-gigs/$id'
      preLoaderRoute: typeof FindGigsIdRouteImport
      parentRoute: typeof FindGigsRoute
    }
    '/book/$handle': {
      id: '/book/$handle'
      path: '/$handle'
      fullPath: '/book/$handle'
      preLoaderRoute: typeof BookHandleRouteImport
      parentRoute: typeof BookRoute
    }
    '/_signedin/welcome': {
      id: '/_signedin/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof SignedinWelcomeRouteImport
      parentRoute: typeof SignedinRoute
    }
    '/_signedin/post-gig': {
      id: '/_signedin/post-gig'
      path: '/post-gig'
      fullPath: '/post-gig'
      preLoaderRoute: typeof SignedinPostGigRouteImport
      parentRoute: typeof SignedinRoute
    }
    '/_signedin/my-roster': {
      id: '/_signedin/my-roster'
      path: '/my-roster'
      fullPath: '/my-roster'
      preLoaderRoute: typeof SignedinMyRosterRouteImport
      parentRoute: typeof SignedinRoute
    }
    '/_signedin/my-gigs': {
      id: '/_signedin/my-gigs'
      path: '/my-gigs'
      fullPath: '/my-gigs'
      preLoaderRoute: typeof SignedinMyGigsRouteImport
      parentRoute: typeof SignedinRoute
    }
    '/_signedin/my-applications': {
      id: '/_signedin/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof SignedinMyApplicationsRouteImport
      parentRoute: typeof SignedinRoute
    }
    '/_signedin/concierge': {
      id: '/_signedin/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof SignedinConciergeRouteImport
      parentRoute: typeof SignedinRoute
    }
    '/_signedin/artist': {
      id: '/_signedin/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof SignedinArtistRouteImport
      parentRoute: typeof SignedinRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/book/confirm/$ref': {
      id: '/book/confirm/$ref'
      path: '/confirm/$ref'
      fullPath: '/book/confirm/$ref'
      preLoaderRoute: typeof BookConfirmRefRouteImport
      parentRoute: typeof BookRoute
    }
    '/api/public/quote-request': {
      id: '/api/public/quote-request'
      path: '/api/public/quote-request'
      fullPath: '/api/public/quote-request'
      preLoaderRoute: typeof ApiPublicQuoteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gigs': {
      id: '/api/public/gigs'
      path: '/api/public/gigs'
      fullPath: '/api/public/gigs'
      preLoaderRoute: typeof ApiPublicGigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/distance': {
      id: '/api/public/distance'
      path: '/api/public/distance'
      fullPath: '/api/public/distance'
      preLoaderRoute: typeof ApiPublicDistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/artists': {
      id: '/api/public/artists'
      path: '/api/public/artists'
      fullPath: '/api/public/artists'
      preLoaderRoute: typeof ApiPublicArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signedin/my-gigs/$id': {
      id: '/_signedin/my-gigs/$id'
      path: '/$id'
      fullPath: '/my-gigs/$id'
      preLoaderRoute: typeof SignedinMyGigsIdRouteImport
      parentRoute: typeof SignedinMyGigsRoute
    }
    '/_signedin/artist/profile': {
      id: '/_signedin/artist/profile'
      path: '/profile'
      fullPath: '/artist/profile'
      preLoaderRoute: typeof SignedinArtistProfileRouteImport
      parentRoute: typeof SignedinArtistRoute
    }
    '/_signedin/artist/intelligence': {
      id: '/_signedin/artist/intelligence'
      path: '/intelligence'
      fullPath: '/artist/intelligence'
      preLoaderRoute: typeof SignedinArtistIntelligenceRouteImport
      parentRoute: typeof SignedinArtistRoute
    }
    '/_signedin/artist/career': {
      id: '/_signedin/artist/career'
      path: '/career'
      fullPath: '/artist/career'
      preLoaderRoute: typeof SignedinArtistCareerRouteImport
      parentRoute: typeof SignedinArtistRoute
    }
    '/_authenticated/admin/verify': {
      id: '/_authenticated/admin/verify'
      path: '/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AuthenticatedAdminVerifyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promoters': {
      id: '/_authenticated/admin/promoters'
      path: '/promoters'
      fullPath: '/admin/promoters'
      preLoaderRoute: typeof AuthenticatedAdminPromotersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gigs': {
      id: '/_authenticated/admin/gigs'
      path: '/gigs'
      fullPath: '/admin/gigs'
      preLoaderRoute: typeof AuthenticatedAdminGigsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/deposits/$ref': {
      id: '/api/public/deposits/$ref'
      path: '/api/public/deposits/$ref'
      fullPath: '/api/public/deposits/$ref'
      preLoaderRoute: typeof ApiPublicDepositsRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/payment-reminders': {
      id: '/api/public/cron/payment-reminders'
      path: '/api/public/cron/payment-reminders'
      fullPath: '/api/public/cron/payment-reminders'
      preLoaderRoute: typeof ApiPublicCronPaymentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/decision-engine': {
      id: '/api/public/cron/decision-engine'
      path: '/api/public/cron/decision-engine'
      fullPath: '/api/public/cron/decision-engine'
      preLoaderRoute: typeof ApiPublicCronDecisionEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings/$ref': {
      id: '/api/public/bookings/$ref'
      path: '/$ref'
      fullPath: '/api/public/bookings/$ref'
      preLoaderRoute: typeof ApiPublicBookingsRefRouteImport
      parentRoute: typeof ApiPublicBookingsRoute
    }
    '/_signedin/artist/intelligence/onboarding': {
      id: '/_signedin/artist/intelligence/onboarding'
      path: '/onboarding'
      fullPath: '/artist/intelligence/onboarding'
      preLoaderRoute: typeof SignedinArtistIntelligenceOnboardingRouteImport
      parentRoute: typeof SignedinArtistIntelligenceRoute
    }
    '/_authenticated/admin/events/$id': {
      id: '/_authenticated/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/new': {
      id: '/_authenticated/admin/bookings/new'
      path: '/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AuthenticatedAdminBookingsNewRouteImport
      parentRoute: typeof AuthenticatedAdminBookingsRoute
    }
    '/_authenticated/admin/bookings/$id': {
      id: '/_authenticated/admin/bookings/$id'
      path: '/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIdRouteImport
      parentRoute: typeof AuthenticatedAdminBookingsRoute
    }
  }
}

interface AuthenticatedAdminBookingsRouteChildren {
  AuthenticatedAdminBookingsIdRoute: typeof AuthenticatedAdminBookingsIdRoute
  AuthenticatedAdminBookingsNewRoute: typeof AuthenticatedAdminBookingsNewRoute
}

const AuthenticatedAdminBookingsRouteChildren: AuthenticatedAdminBookingsRouteChildren =
  {
    AuthenticatedAdminBookingsIdRoute: AuthenticatedAdminBookingsIdRoute,
    AuthenticatedAdminBookingsNewRoute: AuthenticatedAdminBookingsNewRoute,
  }

const AuthenticatedAdminBookingsRouteWithChildren =
  AuthenticatedAdminBookingsRoute._addFileChildren(
    AuthenticatedAdminBookingsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRouteWithChildren
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminGigsRoute: typeof AuthenticatedAdminGigsRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminPromotersRoute: typeof AuthenticatedAdminPromotersRoute
  AuthenticatedAdminVerifyRoute: typeof AuthenticatedAdminVerifyRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventsIdRoute: typeof AuthenticatedAdminEventsIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRouteWithChildren,
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminGigsRoute: AuthenticatedAdminGigsRoute,
  AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
  AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
  AuthenticatedAdminPromotersRoute: AuthenticatedAdminPromotersRoute,
  AuthenticatedAdminVerifyRoute: AuthenticatedAdminVerifyRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEventsIdRoute: AuthenticatedAdminEventsIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SignedinArtistIntelligenceRouteChildren {
  SignedinArtistIntelligenceOnboardingRoute: typeof SignedinArtistIntelligenceOnboardingRoute
}

const SignedinArtistIntelligenceRouteChildren: SignedinArtistIntelligenceRouteChildren =
  {
    SignedinArtistIntelligenceOnboardingRoute:
      SignedinArtistIntelligenceOnboardingRoute,
  }

const SignedinArtistIntelligenceRouteWithChildren =
  SignedinArtistIntelligenceRoute._addFileChildren(
    SignedinArtistIntelligenceRouteChildren,
  )

interface SignedinArtistRouteChildren {
  SignedinArtistCareerRoute: typeof SignedinArtistCareerRoute
  SignedinArtistIntelligenceRoute: typeof SignedinArtistIntelligenceRouteWithChildren
  SignedinArtistProfileRoute: typeof SignedinArtistProfileRoute
}

const SignedinArtistRouteChildren: SignedinArtistRouteChildren = {
  SignedinArtistCareerRoute: SignedinArtistCareerRoute,
  SignedinArtistIntelligenceRoute: SignedinArtistIntelligenceRouteWithChildren,
  SignedinArtistProfileRoute: SignedinArtistProfileRoute,
}

const SignedinArtistRouteWithChildren = SignedinArtistRoute._addFileChildren(
  SignedinArtistRouteChildren,
)

interface SignedinMyGigsRouteChildren {
  SignedinMyGigsIdRoute: typeof SignedinMyGigsIdRoute
}

const SignedinMyGigsRouteChildren: SignedinMyGigsRouteChildren = {
  SignedinMyGigsIdRoute: SignedinMyGigsIdRoute,
}

const SignedinMyGigsRouteWithChildren = SignedinMyGigsRoute._addFileChildren(
  SignedinMyGigsRouteChildren,
)

interface SignedinRouteChildren {
  SignedinArtistRoute: typeof SignedinArtistRouteWithChildren
  SignedinConciergeRoute: typeof SignedinConciergeRoute
  SignedinMyApplicationsRoute: typeof SignedinMyApplicationsRoute
  SignedinMyGigsRoute: typeof SignedinMyGigsRouteWithChildren
  SignedinMyRosterRoute: typeof SignedinMyRosterRoute
  SignedinPostGigRoute: typeof SignedinPostGigRoute
  SignedinWelcomeRoute: typeof SignedinWelcomeRoute
}

const SignedinRouteChildren: SignedinRouteChildren = {
  SignedinArtistRoute: SignedinArtistRouteWithChildren,
  SignedinConciergeRoute: SignedinConciergeRoute,
  SignedinMyApplicationsRoute: SignedinMyApplicationsRoute,
  SignedinMyGigsRoute: SignedinMyGigsRouteWithChildren,
  SignedinMyRosterRoute: SignedinMyRosterRoute,
  SignedinPostGigRoute: SignedinPostGigRoute,
  SignedinWelcomeRoute: SignedinWelcomeRoute,
}

const SignedinRouteWithChildren = SignedinRoute._addFileChildren(
  SignedinRouteChildren,
)

interface BookRouteChildren {
  BookHandleRoute: typeof BookHandleRoute
  BookConfirmRefRoute: typeof BookConfirmRefRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookHandleRoute: BookHandleRoute,
  BookConfirmRefRoute: BookConfirmRefRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface FindGigsRouteChildren {
  FindGigsIdRoute: typeof FindGigsIdRoute
}

const FindGigsRouteChildren: FindGigsRouteChildren = {
  FindGigsIdRoute: FindGigsIdRoute,
}

const FindGigsRouteWithChildren = FindGigsRoute._addFileChildren(
  FindGigsRouteChildren,
)

interface ApiPublicBookingsRouteChildren {
  ApiPublicBookingsRefRoute: typeof ApiPublicBookingsRefRoute
}

const ApiPublicBookingsRouteChildren: ApiPublicBookingsRouteChildren = {
  ApiPublicBookingsRefRoute: ApiPublicBookingsRefRoute,
}

const ApiPublicBookingsRouteWithChildren =
  ApiPublicBookingsRoute._addFileChildren(ApiPublicBookingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SignedinRoute: SignedinRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRouteWithChildren,
  FindGigsRoute: FindGigsRouteWithChildren,
  RequestQuoteRoute: RequestQuoteRoute,
  PayRefRoute: PayRefRoute,
  ApiPublicArtistsRoute: ApiPublicArtistsRoute,
  ApiPublicBookingsRoute: ApiPublicBookingsRouteWithChildren,
  ApiPublicDistanceRoute: ApiPublicDistanceRoute,
  ApiPublicGigsRoute: ApiPublicGigsRoute,
  ApiPublicQuoteRequestRoute: ApiPublicQuoteRequestRoute,
  ApiPublicCronDecisionEngineRoute: ApiPublicCronDecisionEngineRoute,
  ApiPublicCronPaymentRemindersRoute: ApiPublicCronPaymentRemindersRoute,
  ApiPublicDepositsRefRoute: ApiPublicDepositsRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
